/**
 * build-rds-tokens.ts — writes the [RDS] token layers (2.0, issue #13).
 * Run: pnpm build:rds
 *
 *   styles/rds/theme.css       theme roles of the public recipe, from ds-core (light, dark, plate)
 *   styles/rds/foundation.css  type, radius, space, motion, z, elevation
 *   styles/rds/components.css  component tokens, each one var(--theme-role)
 *
 * Fails on a missing alias, an orphan var() or an unused token (see rds-tokens.ts).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { recipes } from "@rojaostudio/ds-core/recipes";
import { emitRdsCss, generateRdsTheme } from "@rojaostudio/ds-core/generate";
import { check, emitComponentsCss, emitFoundationCss, loadAll } from "./rds-tokens";

const pkg = process.cwd();
const out = join(pkg, "styles", "rds");
mkdirSync(out, { recursive: true });

const { tokens, roles, foundation, stylesheets } = loadAll(pkg);
const problems = check(tokens, roles, foundation, stylesheets);

const fail = (title: string, list: string[]) => {
  if (!list.length) return false;
  console.error(`\n✗ ${title} (${list.length})\n  ${list.join("\n  ")}`);
  return true;
};
const failed = [
  fail("alias to a token that does not exist", problems.missingAlias),
  fail("var() that no layer defines", problems.orphanVars),
  fail("component token never used by its stylesheet", problems.unusedTokens),
  fail("component stylesheet reading a theme role instead of its component token", problems.themeRoleInComponent),
  fail("Figma codeSyntax that is not the path with hyphens (fix it in Figma)", problems.codeSyntaxDivergent),
].some(Boolean);
if (failed) process.exit(1);

const header = "/* GENERATED by scripts/build-rds-tokens.ts from ds-core/figma/theme.txt. Do not edit. */\n";
const theme = emitRdsCss(generateRdsTheme(recipes.rojao));
writeFileSync(join(out, "theme.css"), `${header}@layer rds.theme {\n${theme}}\n`);
writeFileSync(join(out, "foundation.css"), emitFoundationCss(foundation));
writeFileSync(join(out, "components.css"), emitComponentsCss(tokens));

// Every component stylesheet, in one file, inside the components layer.
const styles = [...stylesheets].sort((a, b) => a.file.localeCompare(b.file));
writeFileSync(
  join(out, "components-styles.css"),
  `/* GENERATED by scripts/build-rds-tokens.ts from the component stylesheets (components/<name>.css). Do not edit. */\n@layer rds.components {\n` +
    styles.map(({ file, css }) => `/* ${file} */\n${css.trim()}`).join("\n\n") +
    `\n}\n`,
);

// The one stylesheet a consumer imports. The layer order is declared first, so a consumer's
// unlayered CSS always wins over the design system without !important.
writeFileSync(
  join(pkg, "styles", "rds.css"),
  [
    "/* GENERATED by scripts/build-rds-tokens.ts. Import once: @import \"@rojaostudio/ds/styles/rds.css\". */",
    "@layer rds.theme, rds.tokens, rds.components;",
    '@import "./rds/theme.css";',
    '@import "./rds/foundation.css";',
    '@import "./rds/components.css";',
    '@import "./rds/components-styles.css";',
    "",
  ].join("\n"),
);
console.log(
  `✓ styles/rds: ${roles.size} theme roles, ${foundation.length} foundation tokens, ` +
    `${tokens.length} component tokens, ${styles.length} component stylesheet(s)`,
);
