/**
 * build-rds-tokens.ts — writes the [RDS] token layers (2.0, issue #13).
 * Run: pnpm build:rds
 *
 *   styles/rds/theme.css       theme roles of the Rojão brand, one to one with Figma: the brand table
 *                              ds-core/figma/brands/rojao.rds.json (figma/export-brand.js), light, dark, plate
 *   styles/rds/foundation.css  type, radius, space, motion, z, elevation, and the layout/* a stylesheet reads
 *   styles/rds/components.css  component tokens, each one var(--theme-role)
 *
 * Fails on a missing alias, an orphan var() or an unused token (see rds-tokens.ts).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  check,
  emitComponentsCss,
  emitFoundationCss,
  emitThemeCss,
  emitViewportCss,
  loadAll,
  loadBrandTable,
  RDS_LAYER_ORDER,
  usedVars,
} from "./rds-tokens";

const pkg = process.cwd();
const out = join(pkg, "styles", "rds");
mkdirSync(out, { recursive: true });

const { tokens, roles, foundation, viewport, stylesheets } = loadAll(pkg);
// The layout/* numbers of the viewport collection are defined (one media query per breakpoint) when a stylesheet reads them.
const layoutVars = new Set(viewport.tokens.filter((t) => t.name.startsWith("layout/")).map((t) => t.cssVar));
const problems = check(tokens, roles, foundation, stylesheets, layoutVars);

const fail = (title: string, list: string[]) => {
  if (!list.length) return false;
  console.error(`\n✗ ${title} (${list.length})\n  ${list.join("\n  ")}`);
  return true;
};
const failed = [
  fail("alias to a token that does not exist", problems.missingAlias),
  fail("var() that no layer defines", problems.orphanVars),
  fail("component token never used by its stylesheet", problems.unusedTokens),
  fail("component stylesheet reading a theme role instead of its component token", problems.themeRoleInComponent),
  fail("Figma codeSyntax that is not the path with hyphens (fix it in Figma)", problems.codeSyntaxDivergent),
].some(Boolean);
if (failed) process.exit(1);

// The contrast report of the table goes to the console: the table is Figma one to one, a failure is Figma's to fix.
writeFileSync(join(out, "theme.css"), emitThemeCss(loadBrandTable(pkg, "rojao"), (m) => console.warn(`! ${m}`)));
writeFileSync(join(out, "foundation.css"), emitFoundationCss(foundation, emitViewportCss(viewport, usedVars(stylesheets))));
writeFileSync(join(out, "components.css"), emitComponentsCss(tokens));

// Every component stylesheet, in one file, inside the components layer.
const styles = [...stylesheets].sort((a, b) => a.file.localeCompare(b.file));
writeFileSync(
  join(out, "components-styles.css"),
  `/* GENERATED by scripts/build-rds-tokens.ts from the component stylesheets (components/<name>.css). Do not edit. */\n@layer rds.components {\n` +
    styles.map(({ file, css }) => `/* ${file} */\n${css.trim()}`).join("\n\n") +
    `\n}\n`,
);

// The one stylesheet a consumer imports. The layer order is declared first, so a consumer's
// unlayered CSS always wins over the design system without !important. rds.legacy (the deprecated 1.x
// base.css) comes first: with both stylesheets imported, the 2.0 wins wherever their variables collide.
writeFileSync(
  join(pkg, "styles", "rds.css"),
  [
    "/* GENERATED by scripts/build-rds-tokens.ts. Import once: @import \"@rojaostudio/ds/styles/rds.css\". */",
    `@layer ${RDS_LAYER_ORDER};`,
    '@import "./rds/theme.css";',
    '@import "./rds/foundation.css";',
    '@import "./rds/components.css";',
    '@import "./rds/components-styles.css";',
    "",
  ].join("\n"),
);
console.log(
  `✓ styles/rds: ${roles.size} theme roles, ${foundation.length} foundation tokens, ` +
    `${tokens.length} component tokens, ${styles.length} component stylesheet(s)`,
);
