/**
 * rds-tokens.ts — the component token layer of the Figma [RDS] (2.0, issue #13).
 *
 * Inputs (all extracted from Figma, never edited by hand):
 *   - packages/ds/tokens/figma/*.txt       one file per component collection (button/…, input/…)
 *   - packages/ds-core/figma/theme.txt     the theme roles a component token may point to
 *   - packages/ds-core/figma/foundation.txt the non-colour base tokens (type, radius, space…)
 *
 * Output: CSS custom properties. A component token is always `var(--<theme role>)`, never a
 * value, so the brand colour reaches the component through the theme generated by ds-core.
 *
 * Checks (each one fails the build):
 *   1. alias to a role or base token that does not exist
 *   2. `var(--x)` in a component stylesheet that no layer defines (Radix's runtime --radix-* aside)
 *   3. a token of a component that has a stylesheet but never uses it (unless Figma marks it obsolete)
 *   4. a component stylesheet that reads a theme role directly instead of its component token
 *   5. a Figma codeSyntax that is not the path with hyphens (the fix belongs in Figma)
 */
import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { emitRdsCss, rdsThemeFromTable, RDS_TOKEN_SCOPE, type RdsBrandTable } from "@rojaostudio/ds-core/generate";

export type Token = {
  collection: string;
  name: string;
  type: "C" | "F" | "S" | "B";
  value: string;
  cssVar: string;
  /** codeSyntax from Figma when it differs from the path rule. */
  figmaCodeSyntax?: string;
  /** Marked "Obsoleto" in Figma: still emitted for old code, but no stylesheet has to read it. */
  obsolete?: true;
};

export type Foundation = { name: string; type: string; value: string; cssVar: string };

export const pathVar = (name: string) => `--${name.replaceAll("/", "-")}`;

const dataLines = (txt: string) => txt.split(/\r?\n/).filter((l) => l.trim() && !l.startsWith("#"));

export function parseCollection(collection: string, txt: string): Token[] {
  return dataLines(txt).map((line) => {
    const [name, type, value, cs, flag] = line.split("|");
    const cssVar = pathVar(name);
    return {
      collection, name, type: type as Token["type"], value, cssVar,
      ...(cs && cs !== "=" && cs !== cssVar ? { figmaCodeSyntax: cs } : {}),
      ...(flag === "obsolete" ? { obsolete: true as const } : {}),
    };
  });
}

export function parseThemeRoles(txt: string): Set<string> {
  return new Set(dataLines(txt).map((l) => l.split("|")[0]));
}

export function parseFoundation(txt: string): Foundation[] {
  return dataLines(txt).map((l) => {
    const [name, type, value, cssVar] = l.split("|");
    return { name, type, value, cssVar: cssVar || pathVar(name) };
  });
}

/** Value of a component token as CSS. */
export function tokenCss(t: Token): string {
  const alias = t.value.match(/^@(\w+):(.+)$/);
  if (alias) return `var(${pathVar(alias[2])})`;
  if (t.type === "F") return `${t.value}px`;
  return t.value;
}

/** Value of a foundation token as CSS. */
export function foundationCss(f: Foundation): string {
  if (f.type === "S") return f.value.includes(",") || f.name.startsWith("motion/") ? f.value : `"${f.value}"`;
  if (f.type === "E")
    return f.value
      .split(";")
      .map((s) => s.trim().replace(/^(-?\d+) (-?\d+) (-?\d+) (-?\d+) @theme:(.+)$/, (_, x, y, b, sp, role) =>
        `${x}px ${y}px ${b}px ${sp}px var(${pathVar(role)})`))
      .join(", ");
  if (f.name.startsWith("motion/duration")) return `${f.value}ms`;
  if (f.name.startsWith("z/") || f.name.endsWith("/weight")) return f.value;
  return `${f.value}px`;
}

/**
 * The [RDS] Base Tokens collections that foundation.txt flattens (type lives in `base`, space and
 * size in `scale`…). An alias into any of them resolves against the foundation names.
 */
export const FOUNDATION_COLLECTIONS = new Set(["base", "scale", "breakpoint", "motion", "layer"]);

export type Problems = {
  missingAlias: string[];
  orphanVars: string[];
  unusedTokens: string[];
  themeRoleInComponent: string[];
  codeSyntaxDivergent: string[];
};

export function check(
  tokens: Token[],
  roles: Set<string>,
  foundation: Foundation[],
  stylesheets: Array<{ file: string; css: string }>,
  extraDefined: Set<string> = new Set(),
): Problems {
  const base = new Set(foundation.map((f) => f.name));
  // A component token may point to another component token (bottom-bar/leading/min-width → Actions
  // button/size/md/height): the collection is the .txt name, in any case.
  const component = new Set(tokens.map((t) => `${t.collection.toLowerCase()}:${t.name}`));
  const missingAlias: string[] = [];
  for (const t of tokens) {
    const a = t.value.match(/^@(\w+):(.+)$/);
    if (!a) continue;
    const ok =
      a[1] === "theme" ? roles.has(a[2])
      : FOUNDATION_COLLECTIONS.has(a[1]) ? base.has(a[2])
      : component.has(`${a[1].toLowerCase()}:${a[2]}`);
    if (!ok) missingAlias.push(`${t.collection}: ${t.name} → ${t.value}`);
  }

  const defined = new Set<string>([
    ...tokens.map((t) => t.cssVar),
    ...[...roles].map(pathVar),
    ...foundation.map((f) => f.cssVar),
    ...extraDefined,
  ]);
  const orphanVars: string[] = [];
  const themeRoleInComponent: string[] = [];
  const roleVars = new Set([...roles].map(pathVar));
  const used = new Set<string>();
  for (const { file, css } of stylesheets) {
    // Locals (--_x) are the component's own; declarations in the file count as defined.
    const local = new Set([...css.matchAll(/(--[\w-]+)\s*:/g)].map((m) => m[1]));
    for (const m of css.matchAll(/var\(\s*(--[\w-]+)/g)) {
      used.add(m[1]);
      if (roleVars.has(m[1])) themeRoleInComponent.push(`${file}: ${m[1]}`);
      // --radix-*: set at runtime by Radix on the element it positions (trigger width, available height).
      const runtime = m[1].startsWith("--radix-");
      if (!m[1].startsWith("--_") && !runtime && !defined.has(m[1]) && !local.has(m[1])) orphanVars.push(`${file}: ${m[1]}`);
    }
  }

  // A component "has a stylesheet" when a CSS file declares `@tokens <group>` (e.g. button).
  const groups = new Set(stylesheets.flatMap(({ css }) => [...css.matchAll(/@tokens\s+([\w-]+)/g)].map((m) => m[1])));
  const unusedTokens = tokens
    .filter((t) => groups.has(t.name.split("/")[0]) && !used.has(t.cssVar) && !t.obsolete)
    .map((t) => `${t.collection}: ${t.name}`);

  const codeSyntaxDivergent = tokens
    .filter((t) => t.figmaCodeSyntax)
    .map((t) => `${t.collection}: ${t.name} (Figma ${t.figmaCodeSyntax}, code ${t.cssVar})`);

  return {
    missingAlias, orphanVars: [...new Set(orphanVars)], unusedTokens,
    themeRoleInComponent: [...new Set(themeRoleInComponent)], codeSyntaxDivergent,
  };
}

/**
 * Where the token layers are declared. A custom property holding var(--role) is resolved where it
 * is declared, so the component tokens are declared again on every element that switches the theme
 * (.dark, .ds-plate): otherwise a button inside a plate would keep the colours resolved at :root.
 * The list lives in ds-core (RDS_SCOPE_SELECTORS), where emitRdsCss checks a custom scope against it; the
 * generic attributes ([data-rds-scope], [data-rds-mode], [data-rds-plate]) are the way in for any own scope.
 */
export const TOKEN_SCOPE = RDS_TOKEN_SCOPE;

/**
 * The cascade layers of styles/rds.css, lowest first. rds.legacy holds the deprecated 1.x base.css, which
 * declares the same order: whichever of the two stylesheets comes first, the 2.0 layers win over it.
 */
export const RDS_LAYER_ORDER = "rds.legacy, rds.theme, rds.tokens, rds.components";

/** styles/rds/theme.css: the theme of a Figma brand table, in the rds.theme layer. */
export function emitThemeCss(table: RdsBrandTable, warn?: (m: string) => void): string {
  const header =
    "/* GENERATED by scripts/build-rds-tokens.ts from ds-core/figma/brands/" +
    `${table.name}.rds.json (the Figma [RDS] brand table, figma/export-brand.js). Do not edit. */\n`;
  return `${header}@layer rds.theme {\n${emitRdsCss(rdsThemeFromTable(table, { warn }))}}\n`;
}

/** A brand table exported from Figma (ds-core/figma/brands/<name>.rds.json). */
export function loadBrandTable(pkgDir: string, name: string): RdsBrandTable {
  return JSON.parse(readFileSync(join(pkgDir, "..", "ds-core", "figma", "brands", `${name}.rds.json`), "utf8"));
}

export function emitComponentsCss(tokens: Token[]): string {
  const byCollection = new Map<string, Token[]>();
  for (const t of tokens) byCollection.set(t.collection, [...(byCollection.get(t.collection) ?? []), t]);
  const parts = [...byCollection].map(
    ([c, ts]) => `  /* ${c} */\n${ts.map((t) => `  ${t.cssVar}: ${tokenCss(t)};`).join("\n")}`,
  );
  return `/* GENERATED by scripts/build-rds-tokens.ts from tokens/figma/*.txt. Do not edit. */\n@layer rds.tokens {\n${TOKEN_SCOPE} {\n${parts.join("\n\n")}\n}\n}\n`;
}

export function emitFoundationCss(foundation: Foundation[]): string {
  const lines = foundation.map((f) => `  ${f.cssVar}: ${foundationCss(f)};`);
  return `/* GENERATED by scripts/build-rds-tokens.ts from ds-core/figma/foundation.txt. Do not edit. */\n@layer rds.tokens {\n${TOKEN_SCOPE} {\n${lines.join("\n")}\n}\n}\n`;
}

// ── IO ──────────────────────────────────────────────────────────────────────────

function walkCss(dir: string, root: string, out: Array<{ file: string; css: string }> = []) {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) {
      if (e !== "node_modules" && e !== "__tests__") walkCss(p, root, out);
    } else if (e.endsWith(".css")) out.push({ file: relative(root, p).replaceAll("\\", "/"), css: readFileSync(p, "utf8") });
  }
  return out;
}

export function loadAll(pkgDir: string) {
  const figmaDir = join(pkgDir, "tokens", "figma");
  const coreFigma = join(pkgDir, "..", "ds-core", "figma");
  const tokens = readdirSync(figmaDir)
    .filter((f) => f.endsWith(".txt"))
    .sort()
    .flatMap((f) => parseCollection(f.replace(/\.txt$/, ""), readFileSync(join(figmaDir, f), "utf8")));
  const roles = parseThemeRoles(readFileSync(join(coreFigma, "theme.txt"), "utf8"));
  const foundation = parseFoundation(readFileSync(join(coreFigma, "foundation.txt"), "utf8"));
  const stylesheets = walkCss(join(pkgDir, "components"), pkgDir);
  return { tokens, roles, foundation, stylesheets };
}
